import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import {
  AlertCircle, ArrowLeft, ArrowRight, BarChart3, Bell, BookOpen, CalendarDays,
  Check, CheckCircle2, ChevronDown, ClipboardCheck, ClipboardList, Clock3,
  Download, FileCheck2, FileText, GraduationCap, LayoutDashboard, Mail, Menu,
  MessageSquare, MoreHorizontal, Plus, Search, Send, ShieldCheck, Sparkles,
  Trash2, Upload, UserCheck, UserCog, UserMinus, Users, X,
} from "lucide-react";
import logo from "@/assets/website-logo.png";

type IconType = typeof LayoutDashboard;
type Student = { id: string; name: string; course: string; attendance: number; score: number; status: "Active" | "At risk" };

const navGroups: { label: string; items: { key: string; label: string; icon: IconType; badge?: string }[] }[] = [
  { label: "Work center", items: [
    { key: "overview", label: "Command center", icon: LayoutDashboard },
    { key: "directives", label: "Admin directives", icon: ShieldCheck, badge: "3" },
  ] },
  { label: "Student operations", items: [
    { key: "students", label: "Students", icon: Users },
    { key: "attendance", label: "Attendance", icon: UserCheck },
    { key: "assignments", label: "Assignments", icon: ClipboardList },
    { key: "tests", label: "Tests & results", icon: FileCheck2 },
  ] },
  { label: "Academic delivery", items: [
    { key: "syllabus", label: "Syllabus", icon: BookOpen },
    { key: "schedule", label: "Schedule", icon: CalendarDays },
    { key: "communication", label: "Communication", icon: MessageSquare },
  ] },
  { label: "Accountability", items: [
    { key: "reports", label: "Reports", icon: BarChart3 },
    { key: "faculty-record", label: "Faculty record", icon: UserCog },
  ] },
];

const pageTitles: Record<string, [string, string]> = {
  overview: ["Command center", "Today’s academic operations and priorities"],
  directives: ["Administrative directives", "Orders, deadlines and compliance from Administration"],
  students: ["Student roster", "Manage assigned learners and academic status"],
  attendance: ["Attendance management", "Record, review and submit attendance"],
  assignments: ["Assignments", "Create work, monitor submissions and grade"],
  tests: ["Tests & results", "Schedule assessments and review outcomes"],
  syllabus: ["Syllabus execution", "Follow approved curriculum and report progress"],
  schedule: ["Academic schedule", "Classes, duties, meetings and office hours"],
  communication: ["Communication desk", "Announcements and student conversations"],
  reports: ["Reports & compliance", "Evidence for academic and administrative review"],
  "faculty-record": ["Faculty record", "Your attendance, workload and professional profile"],
};

const initialStudents: Student[] = [
  { id: "SL24-101", name: "Aarav Sharma", course: "Physics · Semester 2", attendance: 94, score: 86, status: "Active" },
  { id: "SL24-108", name: "Nandini Rao", course: "Physics · Semester 2", attendance: 88, score: 78, status: "Active" },
  { id: "SL24-116", name: "Ishaan Patel", course: "Physics · Semester 2", attendance: 69, score: 58, status: "At risk" },
  { id: "SL24-121", name: "Meera Krishnan", course: "Physics · Semester 2", attendance: 91, score: 82, status: "Active" },
  { id: "SL24-129", name: "Rohan Kulkarni", course: "Physics · Semester 2", attendance: 76, score: 65, status: "Active" },
];

const Card = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <section className={`rounded-2xl border border-[#d8e8f2] bg-white shadow-[0_10px_30px_-24px_rgba(13,53,104,.4)] ${className}`}>{children}</section>;
const Status = ({ children, tone = "blue" }: { children: React.ReactNode; tone?: "blue" | "teal" | "amber" | "red" | "slate" }) => {
  const colors = { blue: "bg-blue-50 text-blue-700", teal: "bg-teal-50 text-teal-700", amber: "bg-amber-50 text-amber-700", red: "bg-red-50 text-red-700", slate: "bg-slate-100 text-slate-600" };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${colors[tone]}`}>{children}</span>;
};
const PrimaryButton = ({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) => <button onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#1555b6] px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-[#0d438f]">{children}</button>;
const SecondaryButton = ({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) => <button onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 transition hover:border-[#1555b6] hover:text-[#1555b6]">{children}</button>;
const Progress = ({ value, tone = "blue" }: { value: number; tone?: "blue" | "teal" | "amber" }) => <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone === "teal" ? "bg-[#079a9d]" : tone === "amber" ? "bg-amber-500" : "bg-[#1555b6]"}`} style={{ width: `${value}%` }} /></div>;

function FacultyModal({ title, children, onClose, action = "Save" }: { title: string; children: React.ReactNode; onClose: () => void; action?: string }) {
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-black text-[#0d3568]">{title}</h2><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5" /></button></div><div className="space-y-4 p-5">{children}</div><div className="flex justify-end gap-3 border-t p-5"><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><PrimaryButton onClick={onClose}><Check className="h-4 w-4" />{action}</PrimaryButton></div></div></div>;
}

export default function FacultyPortal() {
  const { section = "overview" } = useParams();
  const active = pageTitles[section] ? section : "overview";
  const navigate = useNavigate();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [modal, setModal] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [students, setStudents] = useState(initialStudents);
  const [query, setQuery] = useState("");
  const [attendanceMarked, setAttendanceMarked] = useState<Record<string, boolean>>(() => Object.fromEntries(initialStudents.map(s => [s.id, true])));
  const filteredStudents = useMemo(() => students.filter(s => `${s.name} ${s.id}`.toLowerCase().includes(query.toLowerCase())), [students, query]);
  const go = (key: string) => { navigate(key === "overview" ? "/portal/faculty/workspace" : `/portal/faculty/workspace/${key}`); setMobileOpen(false); };
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2600); };
  const title = pageTitles[active];

  return <main className="min-h-screen bg-[#f3f8fc] font-['Poppins',sans-serif] text-slate-900 lg:grid lg:grid-cols-[278px_1fr]">
    <aside className={`${mobileOpen ? "fixed inset-0 z-50 flex" : "hidden"} lg:sticky lg:top-0 lg:flex lg:h-screen`}>
      <div className="flex h-full w-[278px] shrink-0 flex-col bg-[#0b2d59] p-4 text-white">
        <div className="flex items-center justify-between px-2 py-2"><img src={logo} alt="Simple Lecture" className="h-8 w-auto brightness-0 invert" /><button onClick={() => setMobileOpen(false)} className="lg:hidden"><X className="h-5 w-5" /></button></div>
        <div className="mx-2 mt-5 rounded-2xl bg-gradient-to-br from-[#1555b6] to-[#079a9d] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/15"><GraduationCap className="h-5 w-5" /></span><div><p className="text-xs text-white/65">Faculty workspace</p><p className="font-bold">Dr. Kavya Rao</p></div></div><div className="mt-3 flex items-center gap-2 border-t border-white/15 pt-3 text-xs text-white/70"><span className="h-2 w-2 rounded-full bg-emerald-300" />Physics Department</div></div>
        <nav className="mt-5 flex-1 space-y-4 overflow-y-auto px-1 pb-4">{navGroups.map(group => <div key={group.label}><p className="mb-1.5 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-white/35">{group.label}</p><div className="space-y-1">{group.items.map(item => <button key={item.key} onClick={() => go(item.key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition ${active === item.key ? "bg-white text-[#0d3568] shadow" : "text-white/65 hover:bg-white/10 hover:text-white"}`}><item.icon className="h-[18px] w-[18px]" /><span className="flex-1">{item.label}</span>{item.badge && <span className="rounded-full bg-amber-400 px-2 py-0.5 text-[10px] font-black text-amber-950">{item.badge}</span>}</button>)}</div></div>)}</nav>
        <Link to="/auth" className="flex items-center gap-2 rounded-xl px-3 py-3 text-sm font-semibold text-white/55 hover:bg-white/10 hover:text-white"><ArrowLeft className="h-4 w-4" />Exit faculty preview</Link>
      </div><button onClick={() => setMobileOpen(false)} className="flex-1 bg-slate-950/55 lg:hidden" />
    </aside>

    <section className="min-w-0">
      <header className="sticky top-0 z-30 flex h-[76px] items-center justify-between border-b border-[#d8e8f2] bg-white/95 px-4 backdrop-blur lg:px-7"><div className="flex min-w-0 items-center gap-3"><button onClick={() => setMobileOpen(true)} className="rounded-xl border p-2.5 lg:hidden"><Menu className="h-5 w-5" /></button><div className="min-w-0"><h1 className="truncate text-lg font-black text-[#0d3568] lg:text-xl">{title[0]}</h1><p className="hidden truncate text-xs text-slate-500 sm:block">{title[1]}</p></div></div><div className="flex items-center gap-2"><button className="relative rounded-xl border border-slate-200 p-2.5 text-slate-500"><Bell className="h-5 w-5" /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500 ring-2 ring-white" /></button><div className="hidden items-center gap-3 border-l pl-4 sm:flex"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e5f7fa] font-black text-[#087f85]">KR</span><div><p className="text-sm font-bold">Dr. Kavya Rao</p><p className="text-xs text-slate-400">FAC-1042</p></div><ChevronDown className="h-4 w-4 text-slate-400" /></div></div></header>
      {notice && <div className="fixed right-5 top-24 z-[60] flex items-center gap-3 rounded-2xl bg-[#0d3568] px-5 py-4 text-sm font-semibold text-white shadow-2xl"><CheckCircle2 className="h-5 w-5 text-teal-300" />{notice}</div>}
      <div className="mx-auto max-w-[1500px] p-4 lg:p-7">
        {active === "overview" && <Overview go={go} />}
        {active === "directives" && <Directives flash={flash} />}
        {active === "students" && <StudentsPage students={filteredStudents} query={query} setQuery={setQuery} onAdd={() => setModal("student")} onRemove={(id) => setStudents(list => list.filter(s => s.id !== id))} />}
        {active === "attendance" && <AttendancePage students={students} marked={attendanceMarked} setMarked={setAttendanceMarked} flash={flash} />}
        {active === "assignments" && <AssignmentsPage onCreate={() => setModal("assignment")} flash={flash} />}
        {active === "tests" && <TestsPage onCreate={() => setModal("test")} />}
        {active === "syllabus" && <SyllabusPage flash={flash} />}
        {active === "schedule" && <SchedulePage onCreate={() => setModal("schedule")} />}
        {active === "communication" && <CommunicationPage flash={flash} />}
        {active === "reports" && <ReportsPage flash={flash} />}
        {active === "faculty-record" && <FacultyRecord />}
      </div>
    </section>
    {modal === "student" && <FacultyModal title="Add student to class" onClose={() => setModal(null)} action="Add student"><Field label="Student ID or email" placeholder="Search institutional directory" /><Field label="Assign to" placeholder="Physics · Semester 2" /><InfoNote text="Students can only be added from the Administration-approved directory." /></FacultyModal>}
    {modal === "assignment" && <FacultyModal title="Create assignment" onClose={() => setModal(null)} action="Publish assignment"><Field label="Assignment title" placeholder="e.g. Laws of Motion problem set" /><Field label="Due date" placeholder="Select date and time" /><Field label="Instructions" placeholder="Add guidance for students" textarea /><InfoNote text="Publishing will notify every student in the selected class." /></FacultyModal>}
    {modal === "test" && <FacultyModal title="Schedule a test" onClose={() => setModal(null)} action="Schedule test"><Field label="Test name" placeholder="Unit Test 02" /><div className="grid grid-cols-2 gap-3"><Field label="Duration" placeholder="60 minutes" /><Field label="Maximum marks" placeholder="50" /></div><Field label="Availability" placeholder="Select date and time" /></FacultyModal>}
    {modal === "schedule" && <FacultyModal title="Add schedule item" onClose={() => setModal(null)}><Field label="Title" placeholder="Class, office hour or meeting" /><Field label="Date & time" placeholder="Select slot" /><Field label="Room / meeting link" placeholder="Room 204" /></FacultyModal>}
  </main>;
}

function Field({ label, placeholder, textarea }: { label: string; placeholder: string; textarea?: boolean }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span>{textarea ? <textarea rows={3} placeholder={placeholder} className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 outline-none focus:border-[#1555b6] focus:ring-4 focus:ring-blue-100" /> : <input placeholder={placeholder} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 outline-none focus:border-[#1555b6] focus:ring-4 focus:ring-blue-100" />}</label>; }
function InfoNote({ text }: { text: string }) { return <div className="flex gap-3 rounded-xl bg-blue-50 p-3 text-xs leading-5 text-blue-800"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" />{text}</div>; }

function PageHead({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) { return <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#079a9d]">{eyebrow}</p><h2 className="mt-1 text-2xl font-black text-[#0d3568] lg:text-3xl">{title}</h2><p className="mt-2 text-sm text-slate-500">{copy}</p></div>{action}</div>; }

function Overview({ go }: { go: (key: string) => void }) {
  return <><div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-[#1555b6] to-[#079a9d] p-6 text-white lg:p-8"><div className="absolute -right-10 -top-24 h-64 w-64 rounded-full border-[55px] border-white/10" /><div className="relative"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-white/65"><Sparkles className="h-4 w-4" />Thursday · Academic Week 08</div><h2 className="mt-3 text-3xl font-black lg:text-4xl">Good morning, Dr. Kavya.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/75">Three classes, one attendance submission, and two administrative items need your attention today.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => go("attendance")} className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-[#1555b6]">Take attendance</button><button onClick={() => go("directives")} className="rounded-xl border border-white/30 bg-white/10 px-4 py-2.5 text-sm font-bold">Review directives</button></div></div></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Assigned students","148","6 need attention",Users],["Today’s classes","3","Next at 10:30 AM",CalendarDays],["Pending grading","24","2 assignments",ClipboardCheck],["Syllabus progress","68%","On schedule",BookOpen]].map(([label,value,note,Icon]) => <Card key={label as string} className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-500">{label as string}</p><p className="mt-2 text-3xl font-black text-[#0d3568]">{value as string}</p><p className="mt-2 text-xs font-semibold text-[#079a9d]">{note as string}</p></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#1555b6]"><Icon className="h-5 w-5" /></span></div></Card>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Card className="p-5 lg:p-6"><div className="flex items-center justify-between"><div><h3 className="font-black text-[#0d3568]">Today’s timeline</h3><p className="text-xs text-slate-500">Classes and institutional duties</p></div><button onClick={() => go("schedule")} className="text-sm font-bold text-[#1555b6]">Full schedule</button></div><div className="mt-5 space-y-3">{[["09:00","Physics · Semester 2","Room 204","Completed"],["10:30","Mechanics Lab","Lab 02","Upcoming"],["13:00","Department review","Conference room","Meeting"],["15:00","Office hours","Faculty lounge","Open"]].map(([time,name,room,status]) => <div key={time} className="flex items-center gap-4 rounded-xl border border-slate-100 p-3"><span className="w-12 text-sm font-black text-[#0d3568]">{time}</span><span className="h-10 w-1 rounded-full bg-[#079a9d]" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{name}</p><p className="text-xs text-slate-400">{room}</p></div><Status tone={status === "Completed" ? "teal" : status === "Upcoming" ? "blue" : "slate"}>{status}</Status></div>)}</div></Card>
      <Card className="p-5 lg:p-6"><div className="flex items-center justify-between"><div><h3 className="font-black text-[#0d3568]">Needs attention</h3><p className="text-xs text-slate-500">Priority actions</p></div><AlertCircle className="h-5 w-5 text-amber-500" /></div><div className="mt-5 space-y-3">{[["Submit attendance register","Due today","attendance"],["Acknowledge exam protocol","Due tomorrow","directives"],["Review 6 at-risk students","This week","students"]].map(([title,due,key],i) => <button key={title} onClick={() => go(key)} className="flex w-full items-center gap-3 rounded-xl bg-slate-50 p-3 text-left"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${i === 0 ? "bg-amber-100 text-amber-700" : "bg-blue-100 text-blue-700"}`}>{i+1}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{title}</span><span className="text-xs text-slate-400">{due}</span></span><ArrowRight className="h-4 w-4 text-slate-400" /></button>)}</div></Card></div></>;
}

function Directives({ flash }: { flash: (s: string) => void }) { const directives = [["Mid-semester examination protocol","Office of Academic Affairs","Mandatory","22 Aug 2026","Acknowledge"],["Minimum 75% attendance enforcement","Registrar – Academics","Standing order","Ongoing","Active"],["Internal marks submission window","Controller of Examinations","Deadline","28 Aug 2026","Pending"]]; return <><PageHead eyebrow="Administration → Faculty" title="Orders become accountable action" copy="Read, acknowledge and implement official academic instructions." action={<SecondaryButton><Download className="h-4 w-4" />Policy archive</SecondaryButton>} /><div className="grid gap-4">{directives.map(([title,from,type,due,status],i) => <Card key={title} className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${i === 0 ? "bg-amber-100 text-amber-700" : "bg-blue-50 text-[#1555b6]"}`}><ShieldCheck className="h-6 w-6" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-[#0d3568]">{title}</h3><Status tone={i === 0 ? "amber" : "blue"}>{type}</Status></div><p className="mt-1 text-xs text-slate-500">Issued by {from} · Effective: {due}</p></div><div className="flex gap-2">{status === "Acknowledge" ? <PrimaryButton onClick={() => flash("Directive acknowledged and logged")}><Check className="h-4 w-4" />Acknowledge</PrimaryButton> : <Status tone={status === "Active" ? "teal" : "amber"}>{status}</Status>}<button className="rounded-xl border p-2.5"><MoreHorizontal className="h-4 w-4" /></button></div></div></Card>)}</div></>; }

function StudentsPage({ students, query, setQuery, onAdd, onRemove }: { students: Student[]; query: string; setQuery: (s:string)=>void; onAdd:()=>void; onRemove:(id:string)=>void }) { return <><PageHead eyebrow="Roster control" title="Assigned students" copy="Add from the approved directory, monitor standing, and initiate removal requests." action={<div className="flex gap-2"><SecondaryButton><Upload className="h-4 w-4" />Import list</SecondaryButton><PrimaryButton onClick={onAdd}><Plus className="h-4 w-4" />Add student</PrimaryButton></div>} /><Card><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or student ID" className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm outline-none focus:border-[#1555b6]" /></div><div className="text-xs font-semibold text-slate-500">{students.length} students shown</div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#f5faff] text-xs uppercase tracking-wider text-slate-500"><tr>{["Student","Course","Attendance","Average","Standing","Actions"].map(h=><th key={h} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{students.map(s=><tr key={s.id} className="border-t border-slate-100"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 font-black text-[#1555b6]">{s.name.split(" ").map(n=>n[0]).join("")}</span><div><p className="text-sm font-bold">{s.name}</p><p className="text-xs text-slate-400">{s.id}</p></div></div></td><td className="px-5 py-4 text-sm text-slate-600">{s.course}</td><td className="px-5 py-4"><div className="w-28"><div className="mb-1 flex justify-between text-xs"><span>{s.attendance}%</span></div><Progress value={s.attendance} tone={s.attendance<75?"amber":"teal"} /></div></td><td className="px-5 py-4 text-sm font-bold">{s.score}%</td><td className="px-5 py-4"><Status tone={s.status==="At risk"?"red":"teal"}>{s.status}</Status></td><td className="px-5 py-4"><div className="flex gap-1"><button className="rounded-lg p-2 text-slate-400 hover:bg-blue-50 hover:text-[#1555b6]"><ArrowRight className="h-4 w-4" /></button><button onClick={()=>onRemove(s.id)} title="Request removal" className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><UserMinus className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></Card></>; }

function AttendancePage({ students, marked, setMarked, flash }: { students:Student[]; marked:Record<string,boolean>; setMarked:React.Dispatch<React.SetStateAction<Record<string,boolean>>>; flash:(s:string)=>void }) { const present=Object.values(marked).filter(Boolean).length; return <><PageHead eyebrow="Daily register" title="Physics · Semester 2" copy="Thursday, 20 August 2026 · 10:30 AM · Room 204" action={<PrimaryButton onClick={()=>flash("Attendance submitted to the academic register")}><CheckCircle2 className="h-4 w-4" />Submit attendance</PrimaryButton>} /><div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm text-slate-500">Present</p><p className="mt-1 text-3xl font-black text-emerald-600">{present}</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Absent</p><p className="mt-1 text-3xl font-black text-red-600">{students.length-present}</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Class attendance</p><p className="mt-1 text-3xl font-black text-[#1555b6]">{Math.round(present/students.length*100)}%</p></Card></div><Card className="mt-5"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-black text-[#0d3568]">Mark attendance</h3><p className="text-xs text-slate-500">Tap status to change</p></div><button onClick={()=>setMarked(Object.fromEntries(students.map(s=>[s.id,true])))} className="text-sm font-bold text-[#1555b6]">Mark all present</button></div><div className="divide-y">{students.map(s=><div key={s.id} className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 font-bold text-slate-600">{s.name[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{s.name}</p><p className="text-xs text-slate-400">{s.id}</p></div><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={()=>setMarked(m=>({...m,[s.id]:true}))} className={`rounded-lg px-3 py-2 text-xs font-bold ${marked[s.id]?"bg-emerald-600 text-white":"text-slate-500"}`}>Present</button><button onClick={()=>setMarked(m=>({...m,[s.id]:false}))} className={`rounded-lg px-3 py-2 text-xs font-bold ${!marked[s.id]?"bg-red-500 text-white":"text-slate-500"}`}>Absent</button></div></div>)}</div></Card></>; }

function AssignmentsPage({ onCreate, flash }: { onCreate:()=>void; flash:(s:string)=>void }) { const rows=[["Laws of Motion – Problem Set","Physics · Semester 2","22 Aug","118 / 148","24 pending"],["Rotational Dynamics Lab Report","Mechanics Lab","25 Aug","96 / 120","8 to grade"],["Weekly Concept Reflection","Physics · Semester 1","28 Aug","Draft","Not published"]]; return <><PageHead eyebrow="Learning tasks" title="Assignments & grading" copy="Publish instructions, track submissions and return feedback." action={<PrimaryButton onClick={onCreate}><Plus className="h-4 w-4" />Create assignment</PrimaryButton>} /><div className="grid gap-4">{rows.map(([title,course,due,submitted,state],i)=><Card key={title} className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-[#1555b6]"><ClipboardList className="h-6 w-6" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-[#0d3568]">{title}</h3><Status tone={i===2?"slate":i===1?"amber":"blue"}>{state}</Status></div><p className="mt-1 text-xs text-slate-500">{course} · Due {due}</p><p className="mt-3 text-sm font-semibold text-slate-600">{submitted} submissions</p></div><div className="flex gap-2"><SecondaryButton onClick={()=>flash(i===2?"Draft opened":"Submission review opened")}><FileText className="h-4 w-4" />{i===2?"Edit draft":"Review"}</SecondaryButton><button className="rounded-xl border p-2.5"><MoreHorizontal className="h-4 w-4" /></button></div></div></Card>)}</div></>; }

function TestsPage({ onCreate }: { onCreate:()=>void }) { return <><PageHead eyebrow="Assessment control" title="Tests & examination readiness" copy="Prepare tests within approved patterns and review learning outcomes." action={<PrimaryButton onClick={onCreate}><Plus className="h-4 w-4" />Schedule test</PrimaryButton>} /><div className="grid gap-5 lg:grid-cols-3">{[["Unit Test 02","24 Aug · 10:00","Scheduled","50 marks"],["Mechanics Quiz","Completed 17 Aug","Results ready","20 marks"],["Mid-semester Exam","02 Sep · 09:30","Protocol pending","100 marks"]].map(([title,date,status,marks],i)=><Card key={title} className="p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#1555b6]"><FileCheck2 className="h-5 w-5" /></span><Status tone={i===0?"blue":i===1?"teal":"amber"}>{status}</Status></div><h3 className="mt-5 text-lg font-black text-[#0d3568]">{title}</h3><p className="mt-1 text-sm text-slate-500">{date}</p><p className="mt-4 text-xs font-bold text-slate-400">{marks}</p><button className="mt-5 flex w-full items-center justify-between border-t pt-4 text-sm font-bold text-[#1555b6]">{i===1?"View analytics":"Open test"}<ArrowRight className="h-4 w-4" /></button></Card>)}</div><Card className="mt-5 p-6"><h3 className="font-black text-[#0d3568]">Recent result distribution</h3><div className="mt-5 grid gap-5 sm:grid-cols-4">{[["Class average","74%",74],["Highest score","96%",96],["Pass rate","89%",89],["Needs support","11%",11]].map(([label,val,num],i)=><div key={label as string}><div className="flex justify-between text-sm"><span className="text-slate-500">{label as string}</span><strong>{val as string}</strong></div><div className="mt-3"><Progress value={num as number} tone={i===3?"amber":i===1?"teal":"blue"} /></div></div>)}</div></Card></>; }

function SyllabusPage({ flash }: { flash:(s:string)=>void }) { const units=[["Unit 1 · Mathematical foundations",100,"Completed"],["Unit 2 · Kinematics",92,"In review"],["Unit 3 · Laws of motion",68,"In progress"],["Unit 4 · Work, energy & power",25,"Upcoming"],["Unit 5 · Rotational dynamics",0,"Not started"]]; return <><PageHead eyebrow="Approved curriculum" title="Physics · Semester 2 syllabus" copy="Administration-approved revision 3.2 · Effective academic year 2026–27" action={<SecondaryButton onClick={()=>flash("Syllabus change request created")}><Send className="h-4 w-4" />Request change</SecondaryButton>} /><div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card className="p-5"><div className="flex items-center justify-between border-b pb-4"><div><h3 className="font-black text-[#0d3568]">Curriculum progress</h3><p className="text-xs text-slate-500">42 of 61 planned teaching hours complete</p></div><span className="text-2xl font-black text-[#079a9d]">68%</span></div><div className="mt-5 space-y-5">{units.map(([name,value,status])=><div key={name as string}><div className="mb-2 flex items-center justify-between gap-3"><p className="text-sm font-bold">{name as string}</p><Status tone={status==="Completed"?"teal":status==="In progress"?"blue":status==="In review"?"amber":"slate"}>{status}</Status></div><Progress value={value as number} tone={status==="Completed"?"teal":status==="In review"?"amber":"blue"} /></div>)}</div></Card><div className="space-y-5"><Card className="p-5"><h3 className="font-black text-[#0d3568]">Compliance</h3><div className="mt-4 space-y-3">{["Learning outcomes mapped","Assessment weight aligned","Required lab hours planned"].map(x=><div key={x} className="flex items-center gap-2 text-sm"><CheckCircle2 className="h-4 w-4 text-emerald-600" />{x}</div>)}</div></Card><Card className="p-5"><h3 className="font-black text-[#0d3568]">Next milestone</h3><p className="mt-3 text-3xl font-black">28 Aug</p><p className="mt-1 text-sm text-slate-500">Complete Unit 3 and submit coverage evidence.</p></Card></div></div></>; }

function SchedulePage({ onCreate }: { onCreate:()=>void }) { const days=["Mon 17","Tue 18","Wed 19","Thu 20","Fri 21"]; return <><PageHead eyebrow="Academic calendar" title="Weekly schedule" copy="Teaching, mentoring, departmental duties and office hours." action={<PrimaryButton onClick={onCreate}><Plus className="h-4 w-4" />Add item</PrimaryButton>} /><Card className="overflow-hidden"><div className="grid min-w-[900px] grid-cols-[90px_repeat(5,1fr)] border-b bg-[#f5faff] text-center text-xs font-bold text-slate-500"><div className="p-4">Time</div>{days.map(d=><div key={d} className="border-l p-4">{d}</div>)}</div><div className="min-w-[900px]">{["09:00","10:30","13:00","15:00"].map((time,row)=><div key={time} className="grid grid-cols-[90px_repeat(5,1fr)] border-b last:border-0"><div className="p-4 text-center text-xs font-bold text-slate-400">{time}</div>{days.map((d,col)=>{const show=(row+col)%3!==2; return <div key={d} className="min-h-[104px] border-l p-2">{show&&<div className={`h-full rounded-xl p-3 text-xs ${col%2?"bg-[#e5f7fa] text-[#087f85]":"bg-blue-50 text-[#1555b6]"}`}><p className="font-black">{row===2?"Department duty":row===3?"Office hours":"Physics class"}</p><p className="mt-1 opacity-70">{row===2?"Conference room":"Room 204"}</p></div>}</div>})}</div>)}</div></Card></>; }

function CommunicationPage({ flash }: { flash:(s:string)=>void }) { return <><PageHead eyebrow="Faculty → Students" title="Announcements & messages" copy="Communicate academic instructions with a clear institutional record." action={<PrimaryButton onClick={()=>flash("Announcement composer opened")}><Plus className="h-4 w-4" />New announcement</PrimaryButton>} /><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card><div className="border-b p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input placeholder="Search conversations" className="h-10 w-full rounded-xl bg-slate-50 pl-10 pr-3 text-sm outline-none" /></div></div><div className="divide-y">{[["Physics · Semester 2","Class group","2 new"],["Ishaan Patel","Attendance support","At risk"],["Nandini Rao","Assignment question","Replied"],["Mechanics Lab","Lab group","12 members"]].map(([name,copy,badge],i)=><button key={name} className={`flex w-full items-center gap-3 p-4 text-left ${i===0?"bg-blue-50/60":""}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e5f7fa] font-bold text-[#087f85]">{name[0]}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{name}</span><span className="text-xs text-slate-400">{copy}</span></span><Status tone={i<2?"blue":"slate"}>{badge}</Status></button>)}</div></Card><Card className="flex min-h-[520px] flex-col"><div className="flex items-center gap-3 border-b p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 font-bold text-blue-700">P2</span><div><p className="font-bold">Physics · Semester 2</p><p className="text-xs text-slate-400">148 students · Official class group</p></div></div><div className="flex-1 space-y-4 bg-[#f8fbfd] p-5"><div className="max-w-md rounded-2xl rounded-tl-sm bg-white p-4 text-sm leading-6 shadow-sm">Please confirm whether tomorrow’s lab requires the complete practical record.</div><div className="ml-auto max-w-md rounded-2xl rounded-tr-sm bg-[#1555b6] p-4 text-sm leading-6 text-white">Yes. Bring the updated practical record. The lab begins at 10:30 AM in Lab 02.</div><p className="text-center text-[10px] font-bold uppercase tracking-wider text-slate-400">Announcement · Today</p><div className="mx-auto max-w-xl rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-900"><strong>Reminder:</strong> Unit Test 02 is scheduled for 24 August. Review Units 1–3.</div></div><div className="flex gap-2 border-t p-4"><input placeholder="Write a message to the class…" className="h-11 flex-1 rounded-xl border bg-slate-50 px-3 text-sm outline-none focus:border-[#1555b6]" /><button onClick={()=>flash("Message sent to class preview")} className="grid h-11 w-11 place-items-center rounded-xl bg-[#1555b6] text-white"><Send className="h-4 w-4" /></button></div></Card></div></>; }

function ReportsPage({ flash }: { flash:(s:string)=>void }) { return <><PageHead eyebrow="Evidence to Administration" title="Academic reports" copy="Generate auditable records for review, intervention and accreditation." action={<PrimaryButton onClick={()=>flash("Monthly faculty report generated")}><Download className="h-4 w-4" />Generate report</PrimaryButton>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Attendance compliance","91%",91],["Syllabus coverage","68%",68],["Assignment completion","82%",82],["Pass rate","89%",89]].map(([l,v,n],i)=><Card key={l as string} className="p-5"><p className="text-sm text-slate-500">{l as string}</p><p className="mt-2 text-3xl font-black text-[#0d3568]">{v as string}</p><div className="mt-4"><Progress value={n as number} tone={i===1?"teal":"blue"} /></div></Card>)}</div><Card className="mt-5 p-5"><div className="flex items-center justify-between"><div><h3 className="font-black text-[#0d3568]">Available reports</h3><p className="text-xs text-slate-500">Prepared from faculty activity and student records</p></div></div><div className="mt-5 divide-y">{[["Monthly academic activity report","August 2026","Draft"],["Student attendance shortage list","As of 20 Aug","Ready"],["Internal assessment analysis","Unit Test 01","Ready"],["Syllabus coverage statement","Academic Week 08","Pending update"]].map(([name,period,status])=><div key={name} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-[#1555b6]"><FileText className="h-5 w-5" /></span><div className="flex-1"><p className="text-sm font-bold">{name}</p><p className="text-xs text-slate-400">{period}</p></div><Status tone={status==="Ready"?"teal":status==="Draft"?"blue":"amber"}>{status}</Status><SecondaryButton><Download className="h-4 w-4" />Export</SecondaryButton></div>)}</div></Card></>; }

function FacultyRecord() { return <><PageHead eyebrow="Faculty self-service" title="Professional & attendance record" copy="Your administrative standing, workload, leave and development history." /><div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><Card className="p-6"><div className="flex flex-col items-center text-center"><span className="grid h-24 w-24 place-items-center rounded-3xl bg-gradient-to-br from-[#1555b6] to-[#079a9d] text-3xl font-black text-white">KR</span><h3 className="mt-4 text-xl font-black text-[#0d3568]">Dr. Kavya Rao</h3><p className="text-sm text-slate-500">Assistant Professor · Physics</p><Status tone="teal">Active faculty</Status></div><div className="mt-6 space-y-3 border-t pt-5 text-sm">{[["Employee ID","FAC-1042"],["Department","Physics"],["Joining date","12 July 2021"],["Reporting to","Dean – Sciences"]].map(([k,v])=><div key={k} className="flex justify-between gap-3"><span className="text-slate-500">{k}</span><strong className="text-right">{v}</strong></div>)}</div></Card><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm text-slate-500">Faculty attendance</p><p className="mt-2 text-3xl font-black text-[#0d3568]">96%</p><p className="text-xs text-emerald-600">Current semester</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Teaching load</p><p className="mt-2 text-3xl font-black text-[#0d3568]">18 hrs</p><p className="text-xs text-slate-400">Per week</p></Card><Card className="p-5"><p className="text-sm text-slate-500">Leave balance</p><p className="mt-2 text-3xl font-black text-[#0d3568]">8 days</p><p className="text-xs text-slate-400">Casual leave</p></Card></div><Card className="p-6"><div className="flex items-center justify-between"><h3 className="font-black text-[#0d3568]">Monthly attendance</h3><SecondaryButton><Download className="h-4 w-4" />Statement</SecondaryButton></div><div className="mt-6 grid grid-cols-7 gap-2">{["M","T","W","T","F","S","S"].map((d,i)=><div key={`${d}${i}`} className="text-center text-xs font-bold text-slate-400">{d}</div>)}{Array.from({length:28},(_,i)=><div key={i} className={`grid aspect-square place-items-center rounded-lg text-xs font-bold ${i%7===5||i%7===6?"bg-slate-100 text-slate-400":i===11?"bg-amber-100 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{i+1}</div>)}</div><div className="mt-5 flex flex-wrap gap-4 text-xs text-slate-500"><span className="flex items-center gap-2"><i className="h-3 w-3 rounded bg-emerald-100" />Present</span><span className="flex items-center gap-2"><i className="h-3 w-3 rounded bg-amber-100" />Approved leave</span><span className="flex items-center gap-2"><i className="h-3 w-3 rounded bg-slate-100" />Non-working</span></div></Card></div></div></>; }

